### ISSUE TITLE
Using POI dataset instead of mappings of the mappings.

### ISSUE THREAD

**Issue by species** [TransforMap/transformap.github.io#21]
The map on http://transformap.co/embed/ is currently displaying data from the "mappings of the mappings", which is in no way connected to our SUSY taxonomy. I've uploaded a file which contains only data where the points have the type_of_initiative tag correctly set: https://data.transformap.co/raw/5d6b9d3d32097fd6832200874402cfc3 Could you change the data source in map.js to this url? The structure of this data file should be close to the final one. One of the POIs (Beescoop) has also an image (+author +licence) set, and is a good example in general for the tagging.

**Comment by keikreutler** [comment]
I updated the data source and will use the Beescoop image as tagging reference.

Thanks!
