### ISSUE TITLE
Subcategories not shown

### ISSUE THREAD

**Issue by species** [TransforMap/transformap.github.io#22]
There is a jQuery function to show and hide the subcategories on click, which display beneath the main categories list on the UI, but it is conflicting with the Backbone view. If anyone has an idea of how to fix this before the morning, please do.

**Comment by species** [comment]
I've no idea about the subcategories not displaying on click. I've inspected the generated HTML code, and there where no "onClick" handlers on any of the list items. Another thing: shouldn't there be an &lt;ul> element around the subcategory list elements?

**Comment by keikreutler** [comment]
On the most recent commit, I added a backbonejs click event, and an <ul> element for subcategories.
