### ISSUE TITLE
Map viewer - UI-Design

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap.github.io#24]
- The toolbar looked much better before to the left 
- From the first mockup, the colour in the filter menue looked good, once the sub-segment got open, or a menu got elected.
- points are to small to click (especially e.g. on tablet)
- the indent for the sub-categories could be a little less.

**Comment by species** [comment]
I may add that we need a clustering library (so that the points don't overlap much). I recommend [PruneCluster](https://github.com/SINTEF-9012/PruneCluster), it offers high performance when applying filters.

**Comment by josefkreitmayer** [comment]
- the clustering library topic moved here: https://github.com/TransforMap/transformap-viewer/issues/4
- the POI-size topic moved here: https://github.com/TransforMap/transformap-viewer/issues/2
- the styling issue with the colours in the menu bar are currently abandoned, as functionality has priority.
