### ISSUE TITLE
Map Viewer - populate Initiative-Popup with query data from API

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap.github.io#25]
@keikreutler As far as I understand, we currently have a blockage with the further development of the filter system. A possible next step, while we [resolve the blockag](https://github.com/TransforMap/transformap.github.io/issues/23) could be to work on the connection between the POI-Data-Structure and the Popup on the map.

The popup should include
- [x] The name of the initiative (check)
- [x] Contact information = tel & email (if present for the respective initiative)
- [x] Contact information-Link = Link to contact-page (if present for the respective initiative)
- [x] Address
- [x] Weblink (if present for the respective initiative)
- [x] short description in english (if present for the respective initiative)
- [ ] short description in the local language to be selectable (if present for the respective initiative)
- [ ] type_of_initiative tags (the human readable tag-description)
- [ ] keywords
- [x] Image (dependency - needs further information)
- [x] opening hours (almost not filled by anybody, so neglectible for now)

**Comment by josefkreitmayer** [comment]
@keikreutler great, that you are at it! 

Feedback to the Adress in the bounding box:

I think it would be best to show as this:
Street name [space] house number <br> Postal Code [space] city [comma] country-code

**Comment by keikreutler** [comment]
Sure thing. I am just setting up templates to get the basic content in;
perhaps we could set a date toward Monday to review format and styling all
in one when it's more close to finalised?

**Comment by josefkreitmayer** [comment]
Monday is fine. 
If you don´t mind, I would have a look here and there, and possibly comment with the intention to deliver directional feedback if needed. Small stuff as just now, in order to help testing, and you can trust to getting feedback.

**Comment by keikreutler** [comment]
Okay just wanted to let you know that the appearance is not final at the
moment :)
