### ISSUE TITLE
Map Viewer - 3 level Filter-Menu

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap.github.io#29]
There is 2 aspects to the menu:
1. It should be detailed enough to enable in debth search of the relating filters.
2. It should be simple enough to be also applicable in mobile devlices.

To enable 1., the 3 layered filter structure is highly relevant, in order to present an overview, that is easily understandable as well as detailed in a laptop or desktop browser.

To enable 2. not that much detail is require, so it could be an option to reduce the visibilty of the menu down to the 1st and 2nd level, and hide the 3rd (types of initiatives). If that could be accompanied by a search function, that would be great for mobile. 

**@keikreutler It would be very good to have a conversation early this week. Could you be available sometime tuesday / wednesday in a timeframe early morning - 15:00 New York time?** 

@keikreutler would you like some help with the implementation of the 3-level category menu? On the side of menu-implementation, @species had a look at the JS-Library, and is happy to help with coding if you have problems implementing it.
@species  suggested, that a click on the category, as well as the sub-category already opens the relating POIs. After the initial opening of the map-weblink, they are all loaded to the client, and are then visible in a snap. That could be helpful to my description how to resolve the mobile visualization of the menu. (this is only relevant for applying filters, not the design or implementation of the menu)

**Comment by keikreutler** [comment]
Hi Josef,

Thanks and the 3 tiered structure for the site makes sense, as well as only
two tiers of filtering for the mobile menu.

I'm available to speak tomorrow and Wednesday. However, NY is 6 hours
_behind_ CET, so speaking early morning your time would not work - I'll be
available from 9am NY time (so, a time after 15 CET), if that would work.

**Comment by josefkreitmayer** [comment]
Hello @keikreutler wonderful, that we can meet today. Have a wonderful good morning. 

@species and me will be available from 9am NY on mumble. If you need a little time in the morning, 10:00 am NY is also good for us.

Just drop us a line to know. I also have another call in that timeframes, and need to coordinate. 

looking forward,

Here is a tool for time-differences, that I like to use: [Time-Buddy already with CET and NY](http://www.worldtimebuddy.com/?pl=1&lid=5128581,2761369&h=2761369)

**Comment by keikreutler** [comment]
10 am works. Speak in an hour.

**Comment by josefkreitmayer** [comment]
@keikreutler How are you doing? 
@species and me were waiting today at 16:00 on mumble for the call appointment, that you and @species made.

I would like to ask you, how helpful you see the structure here with the Github Issues. I notice, that I find it much more confusing, than the structure of taiga. https://tree.taiga.io/project/transformap/us/31 It has advantages, as it is more open, it has disadvantages, as it is not so well ordered, and hard to distinguish current production or discussion focus.

What is your impression?

I think @gandhiano also wrote a request to you in the last days about the project for the international food sovereignity indicators
- https://tree.taiga.io/project/gandhiano-iisa-web/kanban 
- https://ecobytes.notes.transformap.co/Budget-international-food-sovereignty-indicators-DFpL1KM2EW8
- It might be helpful to talk, where the project of the map viewer (with current focus ssedas and longterm agnostics) and the drupal based implementation of @gandhiano allign, and separate? 
- How are you doing with the development, that @species told me positively excited about your meeting on wednesday?
- Could you suggest a new timeframe for the short meeting from today?

**Comment by keikreutler** [comment]
@josefkreitmayer I think it would be useful to use the conversations on
github for technical issues, whereas coordination and feedback (related to
overview rather than technical issues) go on Taiga. That said, sorry I
missed the call on Friday I was feeling pretty unwell and woke too late
(11am my time) to cancel. I will update on other things on the Taiga task.

I will respond to @gandhiano's request shortly.

**Comment by josefkreitmayer** [comment]
@keikreutler sorry to hear, that you were unwell. Hope you could recover and wish us a good start in the week. Looking forward to your updates.

**Comment by josefkreitmayer** [comment]
find implementation and documentation here: https://github.com/TransforMap/transformap-viewer
